spring:
  application:
    name: turbine
    
server:
  port: 5001
  
#向eureka注册
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
      
#turbine设置
turbine:
  app-config: order-service,zuul
  cluster-name-expression: new String("default")
